"""
Author: Colin Rioux
Preprocess the pair.csv file generated by pair.py for dp
"""
import pandas as pd

PAIR = "pair.csv"
OUT = "dp-pair.csv"
OUT2 = "test.csv"

in_df = pd.read_csv(PAIR)

data = { "sc": [], "nl": [] }
for index, row in in_df.iterrows():
    codes = row['sc'].split('\\n')
    for code in codes:
        scode = code.strip()
        snl = row['nl'].strip()
        if len(scode) <= 3:
            continue
        if scode.startswith("#"):
            continue
        data['sc'].append(scode)
        data['nl'].append(snl)

result = pd.DataFrame(data)
result.to_csv(OUT, index=False, quoting=1)

result = pd.DataFrame({ "sc": data["sc"] })
result.to_csv(OUT2, index=False, quoting=1)

